config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'contact', to: 'pages#contact'
  resources :villes, only: [:index, :show] do
    resources :lieudits, only: [:index, :new, :create]
    resources :registres, only: [:index, :new, :create]
  end
  resources :lieudits, only: [:show, :edit, :update, :destroy]
  resources :registres, only: [:edit, :update, :destroy] do
    resources :actes, only: [:index, :new, :create]
  end
  resources :actes, only: [:show, :edit, :update, :destroy] do
    resources :commentaires, only: [:index, :new, :create]
    resources :personnes, only: [:index, :new, :create]
  end
  resources :commentaires, only: [:show, :edit, :update, :destroy]
  resources :personnes, only: [:show, :edit, :update, :destroy]
end

app/models/ville.rb
class Ville < ApplicationRecord
  has_many :registres, dependent: :destroy
  has_many :lieudits, dependent: :destroy

  REGIONS = ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d’Azur"]
  DEPARTEMENTS = ["Ain", "Aisne", "Allier", "Alpes-de-Haute-Provence", "Hautes-Alpes", "Alpes-Maritimes", "Ardèche", "Ardennes", "Ariège", "Aube", "Aude", "Aveyron", "Bouches-du-Rhône", "Calvados", "Cantal", "Charente", "Charente-Maritime", "Cher", "Corrèze", "Corse-du-Sud", "Haute-Corse", "Côte-d’Or", "Côtes-d'Armor", "Creuse", "Dordogne", "Doubs", "Drôme", "Eure", "Eure-et-Loir", "Finistère", "Gard", "Haute-Garonne", "Gers", "Gironde", "Hérault", "Ille-et-Vilaine", "Indre", "Indre-et-Loire", "Isère", "Jura", "Landes", "Loir-et-Cher", "Loire", "Haute-Loire", "Loire-Atlantique", "Loiret", "Lot", "Lot-et-Garonne", "Lozère", "Maine-et-Loire", "Manche", "Marne", "Haute-Marne", "Mayenne", "Meurthe-et-Moselle", "Meuse", "Morbihan", "Moselle", "Nièvre", "Nord", "Oise", "Orne", "Pas-de-Calais", "Puy-de-Dôme", "Pyrénées-Atlantiques", "Hautes-Pyrénées", "Pyrénées-Orientales", "Bas-Rhin", "Haut-Rhin", "Rhône", "Haute-Saône", "Saône-et-Loire", "Sarthe", "Savoie", "Haute-Savoie", "Paris", "Seine-Maritime", "Seine-et-Marne", "Yvelines", "Deux-Sèvres", "Somme", "Tarn", "Tarn-et-Garonne", "Var", "Vaucluse", "Vendée", "Vienne", "Haute-Vienne", "Vosges", "Yonne", "Territoire de Belfort", "Essonne", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Val-d'Oise", "Guadeloupe", "Martinique", "Guyane", "La Réunion"]
end

app/controllers/villes_controller.rb
class VillesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @villes = policy_scope(Ville).order(created_at: :desc)
  end

  def show
    @ville = Ville.find(params[:id])
    authorize @ville
  end

  def new
    @ville = Ville.new
    authorize @ville
  end

  def create
    @ville = Ville.new(ville_params)
    @ville.save
    authorize @ville
    redirect_to ville_path(@ville)
  end

  def edit
    @ville = Ville.find(params[:id])
    authorize @ville
  end

  def update
    @ville = Ville.find(params[:id])
    @ville.update(ville_params)
    authorize @ville
    redirect_to ville_path(@ville)
  end

  def destroy
    @ville = Ville.find(params[:id])
    @ville.destroy
    authorize @ville
    redirect_to villes_path
  end

  private

  def ville_params
    params.require(:ville).permit(:name, :departement, :region, :pays)
  end
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/views/villes/edit.html.erb
<h1>Modifier une ville</h1>
<%= simple_form_for @ville do |f| %>
  <%= f.input :name, label: "Nom" %>
  <%= f.input :departement, label: "Département" %>
  <%= f.input :region, label: "Région", collection: Ville::REGIONS %>
  <%= f.input :pays, as: :country, priority: ["France"] %>
  <%= f.button :submit, "Modifier" %>
<% end %>

<%= link_to "Annuler" , ville_path(@ville) %>

app/views/villes/index.html.erb
<div class='container'>

  <h1>
    Liste des villes
  </h1>

  <div id='letters' class='d-flex'>
    <% fi = [] %>
    <% @villes.each do |ville| %>
      <% if ville.name[0..2].include?("La ") || ville.name[0..2].include?("Le ") %>
        <% fi << ville.name[3] %>
      <% elsif ville.name[0..3].include?("Les ")%>
        <% fi << ville.name[4] %>
      <% elsif (ville.name.first == "É") || (ville.name.first == "È") %>
        <% fi << "E" %>
      <% else %>
        <% fi <<  ville.name.first %>
      <% end %>
    <% end %>

    <% [* ('A'..'Z')].each do |letter| %>
      <% if fi.uniq.include?(letter) %>
        <div class='letter letterone' id='<%= letter %>'><%= letter %></div>
      <% else %>
        <div class='letter letterbis' id='<%= letter %>'><%= letter %></div>
      <% end %>
    <% end %>
  </div>

  <div>
    <% @villes.sort.each do |ville| %>
      <% if ville.name[0..2].include?("La ") || ville.name[0..2].include?("Le ") %>
        <div class='<%= ville.name[3] %> ville d-none'>
      <% elsif ville.name[0..3].include?("Les ")%>
        <div class='<%= ville.name[4] %> ville d-none'>
      <% elsif (ville.name.first == "É")|| (ville.name.first == "È") %>
        <div class='E ville d-none'>
      <% else %>
        <div class='<%= ville.name.first %> ville d-none'>
      <% end %>
        <%= link_to ville.name, ville_path(ville) %><%#= link_to "<i class='fas fa-edit'></i>".html_safe, edit_ville_path(ville) %><%#= link_to "<i class='fas fa-trash-alt'></i>".html_safe, ville_path(ville), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %>
      </div>
    <% end %>
  </div>
  <%#= link_to "Créer une nouvelle ville", new_ville_path %>
</div>

app/views/villes/new.html.erb
<h1>Créer une ville</h1>
<%= simple_form_for @ville do |f| %>
  <%= f.input :pays, as: :country, priority: ["France"] %>
  <%= f.input :region, label: "Région", collection: Ville::REGIONS %>
  <%= f.input :departement, label: "Département", collection: Ville::DEPARTEMENTS %>
  <%= f.input :name, label: "Nom" %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Annuler" , villes_path %>

app/views/villes/show.html.erb
<h1><%= @ville.name %>, <%= @ville.departement %><%#= link_to "<i class='fas fa-edit'></i>".html_safe, edit_ville_path(@ville) %><%#= link_to "<i class='fas fa-trash-alt'></i>".html_safe, ville_path(@ville), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></h1>
<p><%= link_to "Liste des lieux-dits pour la ville de " + @ville.name, ville_lieudits_path(@ville) %></p>
<p><%= link_to "Créer un lieu-dit", new_ville_lieudit_path(@ville) %></p>
<p><%= link_to "Liste des registres pour la ville de " + @ville.name, ville_registres_path(@ville) %></p>
<p><%= link_to "Créer un registre", new_ville_registre_path(@ville) %></p>
<p><%= link_to "Toutes les villes", villes_path %></p>