config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'contact', to: 'pages#contact'
  resources :villes, only: [:index, :show] do
    resources :lieudits, only: [:index, :new, :create]
    resources :registres, only: [:index, :new, :create]
  end
  resources :lieudits, only: [:show, :edit, :update, :destroy]
  resources :registres, only: [:edit, :update, :destroy] do
    resources :actes, only: [:index, :new, :create]
  end
  resources :actes, only: [:show, :edit, :update, :destroy] do
    resources :commentaires, only: [:index, :new, :create]
    resources :personnes, only: [:index, :new, :create]
  end
  resources :commentaires, only: [:show, :edit, :update, :destroy]
  resources :personnes, only: [:show, :edit, :update, :destroy]
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  belongs_to :acte
  belongs_to :user

  validates :contenu, presence: true, blank: false
end

app/controllers/commentaires_controller.rb
class CommentairesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def new
    @acte = Acte.find(params[:acte_id])
    @registre = @acte.registre
    @ville = @registre.ville
    @commentaire = Commentaire.new
  end

  def create
    @commentaire = Commentaire.new(commentaire_params)
    @acte = Acte.find(params[:acte_id])
    @registre = @acte.registre
    @ville = @registre.ville
    @commentaire.acte = @acte
    @commentaire.user = current_user
    @commentaire.save
    authorize @commentaire
    if @commentaire.save
      respond_to do |format|
        format.html { redirect_to acte_path(@acte, anchor: "commentaire-#{@commentaire.id}") }
        format.js  # <-- will render `app/views/commentaires/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'actes/show' }
        format.js  # <-- idem
      end
    end
  end

  def edit
    @commentaire = Commentaire.find(params[:id])
    authorize @commentaire
  end

  def update
    @commentaire = Commentaire.find(params[:id])
    @acte = @commentaire.acte
    @commentaire.update(commentaire_params)
    authorize @commentaire
    redirect_to acte_path(@acte)
  end

  def destroy
    @commentaire = Commentaire.find(params[:id])
    @acte = @commentaire.acte
    @commentaire.destroy
    redirect_to acte_path(@acte)
    authorize @commentaire
  end

  def commentaire_params
    params.require(:commentaire).permit(:contenu)
  end
end

app/helpers/commentaires_helper.rb
module CommentairesHelper
end

app/views/commentaires/_contenu.html.erb
<p id="commentaire-<%= commentaire.id %>">
<%= commentaire.user.prenom %> <%= commentaire.user.nom %>
  <br><%= commentaire.contenu %><%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_commentaire_path(commentaire) %><%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, commentaire_path(commentaire), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %>
</p>

app/views/commentaires/_fiabilite.html.erb
<% if @acte.commentaires.count != 0 %>
  <% t = Array.new %>
  <% @acte.commentaires.each do |commentaire| %>
    <% t << commentaire.fiabilite %>
  <% end %>
  <% s = (t.sum/t.count.to_f*100).ceil(1) %>
  <div>
    Fiabilité : <%= s %>% (<%= t.count %> <%= if t.count > 1 then 'votes' else 'vote' end %>)
    <% if s <= 50 && t.count >= 5 %>
      <%= "<i class='fas fa-exclamation-circle'></i>".html_safe %>
    <% elsif s >= 75 && t.count >= 5 %>
      <%= "<i class='fas fa-check-circle'></i>".html_safe %>
    <% else %>
      <%= "<i class='fas fa-question-circle'></i>".html_safe %>
    <% end %>
  </div>
<% end %>

app/views/commentaires/_first.html.erb
<% if current_user != nil && @acte.commentaires.count == 0 %>
  <p>Aucun commentaire.
  <br>Soyez le premier à noter la fiabilité de cet acte et laisser un commentaire</p>
<% elsif current_user == nil && @acte.commentaires.count == 0 %>
  <p>Aucun commentaire.</p>
  <%= link_to "Connectez-vous pour noter cet acte et laisser un commentaire", new_user_session_path %>
<% end %>

app/views/commentaires/_zone.html.erb
<%= simple_form_for([@acte, @commentaire], method: :post, url: acte_commentaires_path(@acte), remote: true) do |f| %>
  <%= f.input :contenu, label: "Commentaire"  %>
  <%= f.button :submit, "Ajouter" %>
<% end %>

app/views/commentaires/create.js.erb
function add(newCom, where, addHTML) {
  const com = document.getElementById(newCom);
  com.insertAdjacentHTML(where, addHTML);
}

if (document.querySelector("#comments")) {
  add('comments', 'beforeend', '<%= j render "commentaires/contenu", commentaire: @commentaire %>');
}

function change(id, Nb) {
  const nb = document.getElementById(id);
  nb.innerHTML = Nb;
}

if (document.querySelector("#zone")) {
  change('zone', '<%= j render "commentaires/zone", commentaire: @commentaire %>');
}

if (document.querySelector("#first")) {
  change('first', '<%= j render "commentaires/first", commentaire: @commentaire %>');
}

app/views/commentaires/edit.html.erb
<%= simple_form_for [@ville, @registre, @acte, @commentaire] do |f| %>
  <%#= f.input :fiabilite, label: "Cet acte est-il fiable?", as: :boolean, as: :radio_buttons, collection: [['OUI', '1'], ['NON', '0']] %>
  <%= f.input :contenu, label: "Commentaire"  %>
  <%= f.button :submit, "Modifier" %>
<% end %>