config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'contact', to: 'pages#contact'
  resources :villes, only: [:index, :show] do
    resources :lieudits, only: [:index, :new, :create]
    resources :registres, only: [:index, :new, :create]
  end
  resources :lieudits, only: [:show, :edit, :update, :destroy]
  resources :registres, only: [:edit, :update, :destroy] do
    resources :actes, only: [:index, :new, :create]
  end
  resources :actes, only: [:show, :edit, :update, :destroy] do
    resources :commentaires, only: [:index, :new, :create]
    resources :personnes, only: [:index, :new, :create]
  end
  resources :commentaires, only: [:show, :edit, :update, :destroy]
  resources :personnes, only: [:show, :edit, :update, :destroy]
end

app/models/lieudit.rb
class Lieudit < ApplicationRecord
  belongs_to :ville

  validates :name, presence: true
end

app/controllers/lieudits_controller.rb
class LieuditsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @ville = Ville.find(params[:ville_id])
    @lieudits = policy_scope(Lieudit).order(created_at: :desc)
  end

  def show
    @lieudit = Lieudit.find(params[:id])
    @ville = @lieudit.ville
    authorize @lieudit
  end

  def new
    @ville = Ville.find(params[:ville_id])
    @lieudit = Lieudit.new
    authorize @lieudit
  end

  def create
    @lieudit = Lieudit.new(lieudit_params)
    @ville = Ville.find(params[:ville_id])
    @lieudit.ville = @ville
    @lieudit.save
    authorize @lieudit
    redirect_to ville_lieudits_path(@ville)
  end

  def edit
    @lieudit = Lieudit.find(params[:id])
    if params["controller"] == "lieudits"
      @ville = @lieudit.ville
    else
      @ville = Ville.find(params[:ville_id])
    end
    authorize @lieudit
  end

  def update
    @lieudit = Lieudit.find(params[:id])
    @ville = @lieudit.ville
    @lieudit.update(lieudit_params)
    authorize @lieudit
    redirect_to ville_lieudits_path(@ville)
  end

  def destroy
    @lieudit = Lieudit.find(params[:id])
    @ville = @lieudit.ville
    @lieudit.destroy
    authorize @lieudit
    redirect_to ville_lieudits_path(@ville)
  end

  private

  def lieudit_params
    params.require(:lieudit).permit(:name)
  end
end

app/helpers/lieudits_helper.rb
module LieuditsHelper
end

app/views/lieudits/edit.html.erb
<h1>Modifier le lieu-dit <%= @lieudit.name %> (<%= @ville.name %>)</h1>
<%= simple_form_for [@lieudit] do |f| %>
  <%= f.input :name, label: "Nom" %>
  <%= f.button :submit, "Modifier" %>
<% end %>
<%= link_to "Retour", ville_path(@ville) %>

app/views/lieudits/index.html.erb
<h1><%= @ville.name %> et ses lieux-dits</h1>
<% if @ville.lieudits.count != 0 %>
  <% @ville.lieudits.each do |lieudit| %>
    <p><%= link_to lieudit.name, lieudit_path(lieudit) %><%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_lieudit_path(lieudit) %><%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, lieudit_path(lieudit), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></p>
  <% end %>
<% else %>
  <p>Aucun lieu-dit</p>
<% end %>
<%= link_to "Créer un nouveau lieu-dit pour " + @ville.name, new_ville_lieudit_path %>
<br><%= link_to "Toutes les villes", villes_path %>

app/views/lieudits/new.html.erb
<h1>Créer un nouveau lieu-dit pour <%= @ville.name %></h1>
<%= simple_form_for [@ville, @lieudit] do |f| %>
  <%= f.input :name, label: "Nom" %>
  <%= f.button :submit, "Créer" %>
<% end %>
<%= link_to "Retour", ville_path(@ville) %>

app/views/lieudits/show.html.erb
<p><%= @lieudit.name + ", " + @lieudit.ville.name %><%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_lieudit_path(@lieudit) %><%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, lieudit_path(@lieudit), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></p>
<%= link_to "Tous les lieus-dits de la ville de " + @lieudit.ville.name, ville_lieudits_path(@ville) %>