config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get 'contact', to: 'pages#contact'
  resources :villes, only: [:index, :show] do
    resources :lieudits, only: [:index, :new, :create]
    resources :registres, only: [:index, :new, :create]
  end
  resources :lieudits, only: [:show, :edit, :update, :destroy]
  resources :registres, only: [:edit, :update, :destroy] do
    resources :actes, only: [:index, :new, :create]
  end
  resources :actes, only: [:show, :edit, :update, :destroy] do
    resources :commentaires, only: [:index, :new, :create]
    resources :personnes, only: [:index, :new, :create]
  end
  resources :commentaires, only: [:show, :edit, :update, :destroy]
  resources :personnes, only: [:show, :edit, :update, :destroy]
end

app/models/acte.rb
class Acte < ApplicationRecord
  belongs_to :registre
  has_many :commentaires, dependent: :destroy
  has_many :fiabilites, dependent: :destroy
  has_many :personnes, dependent: :destroy

  validate :date

  def date
    if datederedaction < datedelevenement
      errors.add(:anneedefin, "La date de rédaction doit être égale ou postérieure à la date de l'évènement")
    end
  end
end

app/controllers/actes_controller.rb
class ActesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @registre = Registre.find(params[:registre_id])
    @ville = @registre.ville
    @actes = policy_scope(Acte).order(created_at: :desc)
  end

  def show
    @acte = Acte.find(params[:id])
    @registre = @acte.registre
    @ville = @registre.ville
    @commentaire = Commentaire.new
    @personne = Personne.new
    authorize @acte
  end

  def new
    @registre = Registre.find(params[:registre_id])
    @ville = @registre.ville
    @acte = Acte.new
    authorize @acte
  end

  def create
    @acte = Acte.new(acte_params)
    @registre = Registre.find(params[:registre_id])
    @ville = @registre.ville
    @acte.registre = @registre
    if @acte.save
      redirect_to new_acte_personne_path(@acte)
    else
      render 'new'
    end
    authorize @acte
  end

  def edit
    @acte = Acte.find(params[:id])
    @registre = @acte.registre
    @ville = @registre.ville
    authorize @acte
  end

  def update
    @acte = Acte.find(params[:id])
    @acte.update(acte_params)
    authorize @acte
    redirect_to acte_path(@acte)
  end

  def destroy
    @acte = Acte.find(params[:id])
    @acte.destroy
    authorize @acte
    redirect_to registre_actes_path(@acte.registre)
  end

  private

  def acte_params
    params.require(:acte).permit(:categorie, :datederedaction, :datedelevenement, :page, :reference)
  end
end

app/helpers/actes_helper.rb
module ActesHelper
end

app/views/actes/edit.html.erb
<h1>Modifier un acte pour le registre des <%= @registre.nature.downcase %> de la ville de <%= @ville.name %>
  <% if @registre.anneededebut == @registre.anneedefin %>
    pour l'année <%= @registre.anneededebut %>
  <% else %>
    pour la période <%= @registre.anneededebut %> - <%= @registre.anneedefin %></p>
  <% end %>
</h1>
<%= simple_form_for [@acte], remote: true do |f| %>
  <% if @registre.nature == "Baptêmes, Mariages, Sépultures" %>
    <%= f.input :categorie, label: "Catégorie", collection: ["Baptêmes", "Mariages", "Sépultures"] %>
  <% elsif @registre.nature == "Naissances, Mariages, Décès" %>
    <%= f.input :categorie, label: "Catégorie", collection: ["Naissances", "Mariages", "Décès"] %>
  <% else %>
    <%= f.input :categorie, as: :hidden, input_html: {value: @registre.nature }  %>
    <p>Catégorie : <%= @registre.nature %></p>
  <% end %>
  <%= f.input :datederedaction, label: "Date de rédaction", as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :datedelevenement, label: "Date de l'évènement", as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :page, label: "Page" %>
  <%= f.button :submit, "Modifier" %>
<% end %>

<%= link_to "Retour", registre_actes_path(@registre) %>

app/views/actes/index.html.erb
<h1>Liste des actes</h1>
<h1>Ville : <%= @ville.name %></h1>
<h1>Registre : <%= @registre.nature %></h1>
<% if @registre.anneededebut != @registre.anneedefin %>
  <h1>Période : <%= @registre.anneededebut + "-" + @registre.anneedefin %>
<% else %>
  <h1>Année : <%= @registre.anneededebut %>
<% end %>
<h1>Côte: <%= @registre.cote%></h1>
<%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_registre_path(@registre) %>
<%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, registre_path(@registre), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></h1>
<br>
<br>
<br>

<% k = [] %>
<% @registre.actes.each do |acte| %>
  <% if ["Mariages", "Publications de mariage", "Divorces"].include?(acte.categorie) && (acte.personnes.where(acteur: "principal").count == 2) %>
    <% k << acte %>
  <% elsif (["Mariages", "Publications de mariage", "Divorces"].include?(acte.categorie) == false) && (acte.personnes.where(acteur: "principal").count == 1) %>
      <% k << acte %>
  <% end %>
<% end %>

<% if k.count == 0 %>
  <p>Pas d'acte pour ce registre</p>
<% else %>
  <p>
    <%= k.count %> <%= if k.count == 1 then "acte disponible" else "actes disponibles" end %> pour le registre des <%= @registre.nature.downcase %> de la ville de <%= @ville.name %> pour
  <% if @registre.anneededebut == @registre.anneedefin %>
      l'année <%= @registre.anneededebut %></p>
    <% else %>
      la période <%= @registre.anneededebut %> - <%= @registre.anneedefin %>
    <% end %>
  </p>
<% end %>

<% k.each do |acte| %>
  <ul>
  <% if ["Mariages", "Publications de mariage", "Divorces"].include?(acte.categorie) && acte.personnes.count > 1 %>
    <li><%= link_to acte.personnes.first.nom.upcase + " " + acte.personnes.first.prenom.capitalize + " & " + acte.personnes.last.nom.upcase + " " + acte.personnes.last.prenom.capitalize + ", "+ acte.categorie + ", " + acte.datederedaction.to_s, acte_path(acte) %>
  <% elsif acte.personnes.where(acteur: "principal").count == 1 %>
    <li><% acte.personnes.where(acteur: "principal").each do |personne| %>
      <%= link_to personne.nom.upcase + " " + personne.prenom.capitalize  + ", " + acte.categorie + ", " + acte.datederedaction.to_s, acte_path(acte) %>
    <% end %>
  <% elsif acte.personnes.count == 0 %>
    error
  <% end %>
  <%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_acte_path(acte) %><%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, acte_path(acte), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></li>
  </ul>
<% end %>

<% c = [] %>
<% @registre.actes.each do |acte| %>
  <% if ["Mariages", "Publications de mariage", "Divorces"].include?(acte.categorie) && (acte.personnes.where(acteur: "principal").count < 2) %>
    <% c << acte %>
  <% elsif (["Mariages", "Publications de mariage", "Divorces"].include?(acte.categorie) == false) && (acte.personnes.where(acteur: "principal").count < 1) %>
    <% c << acte %>
  <% end %>
<% end %>

<% if c.count == 1 %>
  <%= c.count %> acte incomplet
<% elsif c.count > 1 %>
  <%= c.count %> actes incomplets
<% end %>

<% c.each do |a| %>
  <div><%= a.datederedaction %> <%= link_to "Ajouter une personne", new_acte_personne_path(a) %></div>
<% end %>

<br>
<p><%= link_to "Créer un acte pour ce registre", new_registre_acte_path(@registre) %></p>
<p><%= link_to "Tous les Registres de " + @ville.name, ville_registres_path(@ville) %></p>

app/views/actes/new.html.erb
<h1>Créer un acte pour le registre des <%= @registre.nature.downcase %> de la ville de <%= @ville.name %>
  <% if @registre.anneededebut == @registre.anneedefin %>
    pour l'année <%= @registre.anneededebut %>
  <% else %>
    pour la période <%= @registre.anneededebut %> - <%= @registre.anneedefin %></p>
  <% end %>
</h1>


<%= simple_form_for [@registre, @acte], remote: true do |f| %>
  <%= render 'layouts/error_messages', object: f.object %>

  <% if @acte.errors.any? %>
    <ul>
    <% @acte.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>

  <% if f.object.errors.any? %>
    <div>
      <% f.object.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <% if @registre.nature == "Baptêmes, Mariages, Sépultures" %>
    <%= f.input :categorie, label: "Catégorie", collection: ["Baptêmes", "Mariages", "Sépultures"] %>
  <% elsif @registre.nature == "Naissances, Mariages, Décès" %>
    <%= f.input :categorie, label: "Catégorie", collection: ["Naissances", "Mariages", "Décès"] %>
  <% else %>
    <%= f.input :categorie, as: :hidden, input_html: {value: @registre.nature }  %>
    <p>Catégorie : <%= @registre.nature %></p>
  <% end %>
  <%= f.input :reference, label: "Référence" %>
  <%= f.input :datederedaction, label: "Date de rédaction", as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :datedelevenement, label: "Date de l'évènement", as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :page, label: "Page" %>
  <%= f.button :submit, "Créer" %>
<% end %>

<%= link_to "Retour", registre_actes_path(@registre) %>

app/views/actes/show.html.erb
<% j = @acte.datederedaction.strftime("%A") %>
<% if j == "Monday" %>
  <% j = "Lundi" %>
<% elsif j == "Tuesday" %>
  <% j = "Mardi" %>
<% elsif j == "Wednesday" %>
  <% j = "Mercredi" %>
<% elsif j == "Thursday" %>
  <% j = "Jeudi" %>
<% elsif j == "Friday" %>
  <% j = "Vendredi" %>
<% elsif j == "Saturday" %>
  <% j = "Samedi" %>
<% elsif j == "Sunday" %>
  <% j = "Dimanche" %>
<% end %>

<% m = @acte.datederedaction.strftime("%B") %>
<% if m == "January" %>
  <% m = "janvier" %>
<% elsif m == "Fabruary" %>
  <% m = "février" %>
<% elsif m == "March" %>
  <% m = "mars" %>
<% elsif m == "April" %>
  <% m = "avril" %>
<% elsif m == "May" %>
  <% j = "mai" %>
<% elsif m == "June" %>
  <% m = "juin" %>
<% elsif m == "July" %>
  <% m = "juillet" %>
<% elsif m == "August" %>
  <% m = "août" %>
<% elsif m == "September" %>
  <% m = "septembre" %>
<% elsif m == "October" %>
  <% m = "octobre" %>
<% elsif m == "November" %>
  <% m = "novembre" %>
<% elsif m == "December" %>
  <% m = "décembre" %>
<% end %>

<% @acte.personnes.where(acteur: "principal").each do |personne| %>
  <div><%= personne.nom.upcase + " " + personne.prenom.capitalize %></div>
<% end %>
<div><%= @acte.categorie %> - <%= j %> <%= @acte.datederedaction.strftime("%d") %> <%= m %> <%= @acte.datederedaction.year %><%= link_to "<i class='fas fa-edit'></i>".html_safe, edit_acte_path(@acte) %><%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, acte_path(@acte), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer?"} %></div>
<div>Ville : <%= @ville.name %></div>

<br>
<% if @acte.personnes.count != 0 %>
  <p>Liste des personnes apparaissant sur cet acte :</p>
  <% if @acte.personnes.where(acteur: "principal") != 0 %>
    <p>Acteurs principaux :</p>
    <ul>
      <% @acte.personnes.where(acteur: "principal").each do |personne| %>
        <li><%= personne.nom.upcase + " " + personne.prenom.capitalize %></li>
      <% end %>
    </ul>
  <% end %>
  <% if @acte.personnes.where(acteur: "secondaire").count != 0 %>
    <p>Acteurs secondaires :</p>
    <ul>
      <% @acte.personnes.where(acteur: "secondaire").each do |personne| %>
          <li><%= personne.nom.upcase + " " + personne.prenom.capitalize %>
            <% if personne.lien != nil %>
              <% if personne.sexe == "F" %>
                <% if personne.lien == "Père/Mère" %>
                  <%= ", mère" %>
                <% elsif personne.lien == "Frère/Soeur" %>
                  <%= ", soeur" %>
                <% elsif personne.lien != nil %>
                  <%= personne.lien %>
                <% end %>
              <% elsif personne.sexe == "M" %>
                <% if personne.lien == "Père/Mère" %>
                  <%= ", père" %>
                <% elsif personne.lien == "Frère/Soeur" %>
                  <%= ", frère" %>
                <% elsif personne.lien != nil %>
                  <%= ", " + personne.lien.downcase %>
                <% end %>
              <% end %>
            <% end %>
            <%= if (personne.role != nil) && (personne.lien != nil) then " et " + personne.role.downcase end %>
            <%= if (personne.role != nil) && (personne.lien == nil) then ", " + personne.role.downcase end %>
          </li>
      <% end %>
    </ul>
  <% end %>
  <% else %>
  <p>Aucune personne rattachée à cet acte</p>
<% end %>

<br>
<%= link_to "Créer une personne associée à cet acte", new_acte_personne_path(@acte) %>

<br><br>
<div id='first'>
  <%= render 'commentaires/first' %>
</div>

<div id='zone'>
  <%= render 'commentaires/zone' %>
</div>

<br>
<div id='comments'>
  <% @acte.commentaires.each do |commentaire| %>
    <%= render 'commentaires/contenu', commentaire: commentaire %>
  <% end %>
</div>

<% if @registre.anneededebut == @registre.anneedefin %>
  <%= link_to 'Liste des actes pour le registre des ' + @registre.nature.downcase + ' de la ville de ' + @ville.name + " pour l'année " + @registre.anneededebut, registre_actes_path(@registre) %>
<% else %>
  <%= link_to 'Tous les actes pour le registre des ' + @registre.nature.downcase + ' de la ville de ' + @ville.name + " pour la période " + @registre.anneededebut + "-" + @registre.anneedefin, registre_actes_path(@registre) %>
<% end %>